In [3]:
import pandas as pd
import plotly.express as px

In [4]:

data = pd.read_csv("flipkart_sample_dataset.csv")
data.head()

,product_id,product_name,category,brand,price,rating,reviews,discount_percent
0,1,Apple Product 1,Sports,Apple,3478,4.4,2011,28
1,2,Apple Product 2,Fashion,Apple,71682,2.7,3461,4
2,3,Apple Product 3,Electronics,Apple,28857,3.1,4936,3
3,4,Adidas Product 4,Beauty,Adidas,71626,3.5,3684,35
4,5,Nike Product 5,Electronics,Nike,55592,3.4,1278,27

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_id        200 non-null    int64
 1   product_name      200 non-null    str
 2   category          200 non-null    str
 3   brand             200 non-null    str
 4   price             200 non-null    int64
 5   rating            200 non-null    float64
 6   reviews           200 non-null    int64
 7   discount_percent  200 non-null    int64
dtypes: float64(1), int64(4), str(3)
memory usage: 12.6 KB

In [6]:
data.describe()

       product_id         price      rating     reviews  discount_percent
count  200.000000    200.000000  200.000000   200.00000        200.000000
mean   100.500000  40184.750000    3.758000  2755.14000         35.555000
std     57.879185  23577.643863    0.714414  1516.06914         19.223545
min      1.000000    350.000000    2.500000    50.00000          0.000000
25%     50.750000  18065.500000    3.200000  1314.25000         19.000000
50%    100.500000  38993.000000    3.750000  2944.00000         35.500000
75%    150.250000  61217.250000    4.400000  4267.75000         52.000000
max    200.000000  79671.000000    5.000000  4997.00000         70.000000

In [8]:
import sys
!{sys.executable} -m pip install nbformat --break-system-packages

Collecting nbformat
  Using cached nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Collecting fastjsonschema>=2.15 (from nbformat)
  Using cached fastjsonschema-2.21.2-py3-none-any.whl.metadata (2.3 kB)
Collecting jsonschema>=2.6 (from nbformat)
  Using cached jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in C:\Users\HP\AppData\Roaming\Python\Python314\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in C:\Users\HP\AppData\Roaming\Python\Python314\site-packages (from nbformat) (5.14.3)
Collecting attrs>=22.2.0 (from jsonschema>=2.6->nbformat)
  Using cached attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=2.6->nbformat)
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=2.6->nbformat)
  Using cached referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=2.6->nbformat)
  Using cached rpds_py-0.30.0-cp314-cp314-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\HP\AppData\Roaming\Python\Python314\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.9.4)
Using cached nbformat-5.10.4-py3-none-any.whl (78 kB)
Using cached fastjsonschema-2.21.2-py3-none-any.whl (24 kB)
Using cached jsonschema-4.26.0-py3-none-any.whl (90 kB)
Using cached attrs-25.4.0-py3-none-any.whl (67 kB)
Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Using cached referencing-0.37.0-py3-none-any.whl (26 kB)
Using cached rpds_py-0.30.0-cp314-cp314-win_amd64.whl (228 kB)
Installing collected packages: fastjsonschema, rpds-py, attrs, referencing, jsonschema-specifications, jsonschema, nbformat

   ---------------------------------------- 0/7 [fastjsonschema]
   ----------- ---------------------------- 2/7 [attrs]
   ----------- ---------------------------- 2/7 [attrs]
   ----------- ---------------------------- 2/7 [attrs]
   ----------- ---------------------------- 2/7 [attrs]
   ----------------- ---------------------- 3/7 [referencing]
   ----------------- ---------------------- 3/7 [referencing]
   ---------------------- ----------------- 4/7 [jsonschema-specifications]
   ---------------------------- ----------- 5/7 [jsonschema]
   ---------------------------- ----------- 5/7 [jsonschema]
   ---------------------------- ----------- 5/7 [jsonschema]
   ---------------------------- ----------- 5/7 [jsonschema]
   ---------------------------------- ----- 6/7 [nbformat]
   ---------------------------------- ----- 6/7 [nbformat]
   ---------------------------------- ----- 6/7 [nbformat]
   ---------------------------------- ----- 6/7 [nbformat]
   ---------------------------------- ----- 6/7 [nbformat]
   ---------------------------------- ----- 6/7 [nbformat]
   ---------------------------------- ----- 6/7 [nbformat]
   ---------------------------------------- 7/7 [nbformat]

Successfully installed attrs-25.4.0 fastjsonschema-2.21.2 jsonschema-4.26.0 jsonschema-specifications-2025.9.1 nbformat-5.10.4 referencing-0.37.0 rpds-py-0.30.0

  WARNING: The script jsonschema.exe is installed in 'c:\Users\HP\AppData\Roaming\uv\python\cpython-3.14-windows-x86_64-none\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script jupyter-trust.exe is installed in 'c:\Users\HP\AppData\Roaming\uv\python\cpython-3.14-windows-x86_64-none\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [1]:
import plotly.graph_objects as go

fig = go.Figure(data=go.Bar(y=[2,3,1]))
fig.show()

In [2]:
import plotly.graph_objects as go
import pandas as pd

# Load dataset
data = pd.read_csv("flipkart_sample_dataset.csv")

fig = go.Figure()

# Scatter Plot (Price vs Rating)
fig.add_trace(go.Scatter(
    x=data['price'],
    y=data['rating'],
    mode='markers',
    name='Scatter',
    visible=True
))

# Bar Chart (Products per Category)
category_count = data['category'].value_counts()
fig.add_trace(go.Bar(
    x=category_count.index,
    y=category_count.values,
    name='Bar',
    visible=False
))

# Histogram (Price Distribution)
fig.add_trace(go.Histogram(
    x=data['price'],
    name='Histogram',
    visible=False
))

# Box Plot (Rating Distribution by Brand)
fig.add_trace(go.Box(
    x=data['brand'],
    y=data['rating'],
    name='Box Plot',
    visible=False
))

# Line Chart (Average Price by Brand)
avg_price = data.groupby("brand")["price"].mean()

fig.add_trace(go.Scatter(
    x=avg_price.index,
    y=avg_price.values,
    mode='lines+markers',
    name='Line Chart',
    visible=False
))

# Dropdown Menu
fig.update_layout(
    title="Flipkart Product Data Analysis",
    updatemenus=[
        dict(
            buttons=list([
                dict(label="Scatter Plot",
                     method="update",
                     args=[{"visible":[True, False, False, False, False]},
                           {"title":"Price vs Rating"}]),

                dict(label="Bar Chart",
                     method="update",
                     args=[{"visible":[False, True, False, False, False]},
                           {"title":"Products per Category"}]),

                dict(label="Histogram",
                     method="update",
                     args=[{"visible":[False, False, True, False, False]},
                           {"title":"Price Distribution"}]),

                dict(label="Box Plot",
                     method="update",
                     args=[{"visible":[False, False, False, True, False]},
                           {"title":"Rating Distribution by Brand"}]),

                dict(label="Line Chart",
                     method="update",
                     args=[{"visible":[False, False, False, False, True]},
                           {"title":"Average Price by Brand"}]),
            ]),
            direction="down"
        )
    ]
)

fig.show()